version: '3.1'

services:

  qrks_db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: projekt
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped



  mikrostoritev:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://qrks_db:5432/projekt
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=root
    depends_on:
      - qrks_db



volumes:
  postgres: